### ISSUE TITLE
Deprecation: Use babel-preset-env instead of yearly preset

### ISSUE THREAD

**Issue by dkarter** [hashrocket/tilex#155]
Deprecation warning on Travis CI:

```
npm WARN deprecated babel-preset-es2016@6.24.1: We're really excited that you're trying to use ES2016 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates
```

Implementation example:

https://github.com/storybooks/storybook/pull/1668/files

**Comment by jwworth** [comment]
Does anybody want to work on this? I took a swing at it last month and struck out. I'd like to see it fixed but am planning to close if there isn't interest in a patch. @dkarter
