### ISSUE TITLE
Restore Guest Posting Feature

### ISSUE THREAD

**Issue by jwworth** [hashrocket/tilex#186]
In the Rails application, we could whitelist friends of our company/alumni, without a `hashrocket.com` email address, so that they could post on the site.

We should built this feature again for the Elixir app.

**Comment by jwworth** [comment]
More information:

Given I visit `/admin`
And I sign in with a non-Hashrocket email that is whitelisted (i.e. `friend@example.com`)
Then I am signed in

Given I visit `/admin`
And I sign up with a non-Hashrocket email that is whitelisted (i.e. `friend@example.com`)
Then I am signed in and a new user is created

**Comment by codyjroberts** [comment]
I could tackle this.  Would you like it to be configured as an environmental variable?  Possibly a comma separated list of emails?  Or just keep it simple with a list in `config/prod.exs` e.g.

```
config :tilex, :guest_whitelist, [
  "friendof@hashrocket.com"
]
```

**Comment by jwworth** [comment]
@codyjroberts awesome! 👍  Environmental variable would be best; we want it to be customizable by any fork of the project, and keep user emails out of the codebase.

**Comment by codyjroberts** [comment]
OH man totally forgot about this.  Sorry!  I'll knock this out tomorrow.

**Comment by jwworth** [comment]
This is complete.
