### ISSUE TITLE
Add JavaScript CTAs

### ISSUE THREAD

**Issue by jwworth** [hashrocket/tilex#261]
Given I visit a JavaScript, React, or other JS-related channel show page
Then I see copy explaining the type of work we do with those technologies

**Comment by hashrocketeer** [comment]
For context, this is the footer shown beneath our Vim TIL's on Hashrocket's instance:

![image](https://user-images.githubusercontent.com/317960/42113864-7d7a27dc-7bb2-11e8-9446-db4714689d6d.png)
