### ISSUE TITLE
AppSignal Error In Test

### ISSUE THREAD

**Issue by jwworth** [hashrocket/tilex#265]
# Steps to reproduce

### Expected behavior

When we run our tests
Then AppSignal should run quietly with no errors

### Actual behavior

When we run our tests
Then AppSignal errors with `Error loading NIF, AppSignal integration disabled!` 

![image](https://user-images.githubusercontent.com/2782858/36108608-d8bc78c0-0fe2-11e8-80e7-26df336ed899.png)

**Comment by tmock12** [comment]
@jwworth try recompiling it `mix deps.compile appsignal`
