### ISSUE TITLE
Improvement to twitter card descriptions

### ISSUE THREAD

**Issue by jbranchaud** [hashrocket/tilex#267]
<img width="618" alt="screen shot 2018-02-22 at 4 42 36 pm" src="https://user-images.githubusercontent.com/694063/36568421-8e3aed12-17ef-11e8-8244-0bffd3128b30.png">

The description for this TIL on the twitter card is overtaken by the markdown link. I'd suggest using the rendered text rather than the raw markdown for the twitter card descriptions.

**Comment by jbranchaud** [comment]
❤️

**Comment by dkarter** [comment]
I don't think that's possible to have a `<a href...>` link in the card description - that would be considered HTML injection that twitter will have to sanitize somehow. Doubtful they support that.

If you are talking about rendering the text through a markdown parser that strips out the links and just gives you text - that's a different thing - might be possible. The markdown parser we use (Earmark) has [support for returning the parse tree from a markdown text](https://github.com/pragdave/earmark/blob/74be18c59232466865d092785d30d3eed718d8c6/lib/earmark.ex#L335). So you can probably extract all text portions from it with a wrapping function.

**Comment by jwworth** [comment]
Fixed with #287.
