### ISSUE TITLE
Name of the repository

### ISSUE THREAD

**Issue by jbranchaud** [hashrocket/tilex#3]
I think it would be helpful if this repo took on a name that makes it clear that it is an elixir version of the hr-til project.

I am trying to open this up to conversation. My two suggestions would be:

- `tilex`
- `hr-tilex`

thoughts?

**Comment by jwworth** [comment]
Great idea! I never liked the HR-TIL name-- it just kind of stuck.

Tilex is cool. It fits the pattern of other Elixir projects I've seen.

**Comment by jbranchaud** [comment]
I'll make the change!
