### ISSUE TITLE
Broken code on TIL "Mix tasks accessing the db with `Mix.Ecto`"

### ISSUE THREAD

**Issue by axelson** [hashrocket/tilex#311]
I wasn't able to find a good place to report issues with the code posted in specific TIL so I am posting here about ["Mix tasks accessing the db with `Mix.Ecto`"](https://til.hashrocket.com/posts/k4zie79ydb-mix-tasks-accessing-the-db-with-mixecto). The code in there is broken because it relies on an Ecto private API that has been changed in Ecto 3.0. Specifically `Mix.Ecto.ensure_started/2` no longer exists. Here is proof that `Mix.Ecto` is considered a private API: https://github.com/elixir-ecto/ecto/issues/1586#issuecomment-233301683

**Comment by chriserin** [comment]
@axelson thanks for the heads up.  We haven't converted to 3.0 yet that's def on the todo list.
