### ISSUE TITLE
Updating a post with validation errors raises an error

### ISSUE THREAD

**Issue by dillonhafer** [hashrocket/tilex#334]
# Steps to reproduce

### Expected behavior

Given there is a post
And the post title limit is 50 chars
When I edit that post
And I set the title to 51 chars
Then I see an error "Title is too long"

### Actual behavior

Given there is a post
And the post title limit is 50 chars
When I edit that post
And I set the title to 51 chars
Then I see an error "...that something is broken"

**Comment by jwworth** [comment]
I'm working on this.
