### ISSUE TITLE
Tilex keeps asking for basic authentication despite the variable being unset

### ISSUE THREAD

**Issue by Quintasan** [hashrocket/tilex#535]
### Steps to reproduce

I had to rename your `.env` to `tilex.env` since `.env` is read by Docker Compose and someone thought it's a perfectly good idea to remove support for lines beginning with `export` (https://github.com/docker/compose/issues/6511)

```
# .env
### docker-compose specific lines
### Do not change them unless you are using docker-compose
COMPOSE_PROJECT_NAME=tilex

POSTGRES_USER=tilex
POSTGRES_PASSWORD=tilex
POSTGRES_DB=tilex
```

```
# tilex.env
export ORGANIZATION_NAME="Applover"
export ENABLE_BASIC_AUTH=
export BASIC_AUTH_USERNAME=
export BASIC_AUTH_PASSWORD=
export CANONICAL_DOMAIN="https://til.applover.pl"
export HOSTED_DOMAIN="applover.pl"
export GUEST_AUTHOR_WHITELIST=
export DATE_DISPLAY_TZ=Europe/Warsaw
export ASYNC_FEATURE_TEST=yes

export SECRET_KEY_BASE="ohthismustbereallysecure"

# Google
export GOOGLE_CLIENT_ID="sth"
export GOOGLE_CLIENT_SECRET="secret"

# Slack
export slack_post_endpoint=

# Twitter
export twitter_access_token=
export twitter_access_token_secret=
export twitter_consumer_key=
export twitter_consumer_secret=
export DEFAULT_TWITTER_HANDLE=

# Appsignal
export APPSIGNAL_APP_NAME=
export APPSIGNAL_APP_ENV=
export APPSIGNAL_PUSH_API_KEY=

# Imgur
export IMGUR_CLIENT_ID=

# Database connection
export DATABASE_URL="ecto://tilex:tilex@db:5432/tilex"
export PORT=4000
```

```
git clone https://github.com/Quintasan/tilex.git
cd tilex
git checkout docker-compose
docker-compose build
docker-compose up
xdg-open localhost:4000
```

### Expected behavior

Tilex shouldn't ask for Basic Authentication credentials

### Actual behavior

Tilex asks about Basic Authentication credentials

### Suggested fix

Can we make the configuration depend on the value of the variable instead of relying on things being set or unset? Something like `if String.equivalent?(System.get_env("ENABLE_BASIC_AUTH"), "true"))`

**Comment by morganchristiansson** [comment]
```pip install docker-compose==1.23.2``` also fixes the issue

**Comment by Quintasan** [comment]
This, of course, assumes one installed docker-compose via pip and is able
to do that. Most people use the latest binary and I think we'd rather be
compatible with that.

Śr., 4 wrz 2019, 16:35 użytkownik Morgan Christiansson <
notifications@github.com> napisał:

**Comment by Quintasan** [comment]
Oh, this is actually not a problem with docker-compose per se. As you can
see in the Docker files I explicitly source the `tilex.env` file. The
variable is defined but unset and it doesn't work.

Śr., 4 wrz 2019, 16:38 użytkownik Michał Zając <michal.zajac@gmail.com>
napisał:

**Comment by morganchristiansson** [comment]
That should work.. You're not really linking your code... You can also set them via docker-compose.yaml https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option

The main .env is not configurable though.

**Comment by Quintasan** [comment]
There's a link to my fork in the bug report that allows you to reproduce
the issue :)


śr., 4 wrz 2019, 16:49 użytkownik Morgan Christiansson <
notifications@github.com> napisał:

**Comment by Quintasan** [comment]
@morganchristiansson is there anything else I can do to help you reproduce the issue?

**Comment by jwworth** [comment]
Closing; I believe #559 captures the larger issue here.
