### ISSUE TITLE
Like is split into "Like" and "Used"

### ISSUE THREAD

**Issue by pcapel** [hashrocket/tilex#640]
# As a TIL Admin I want to know which posts have been most useful
When ranking the TILs, the current metric is whether or not viewers "like" the post.  This is a nice metric, but it fails to capture a relevant piece of information, whether or not they _used_ it.

I'm wondering if it would be worthwhile to implement an "I used this" button that was distinct from the "like" button.  This would allow people to click on something that was slightly different from just enjoying or appreciating the content of a post.  Furthermore, I think that it should be a simple counter.  That is, if I press it, within a day I could press it again.  This way a person could click and count how many times they used an older post.

I came to this idea after watching the way that @jwworth uses TIL as a knowledge repository.  I realized that we might be missing out on some valuable information about how we ourselves are using TIL by not looking at whether or not we're coming back to specific posts.

I'm open to ideas on how this could be implemented. But I think that it should be conditionally displayed if the user has already liked the post.  That way we keep the visual clutter to a minimum.

**Comment by jwworth** [comment]
Thanks for the idea, @pcapel!

Our like system is an MVP that never graduated. It has flaws, as some folks have discovered: https://hashrocket.com/blog/posts/like-attack-postmortem. And it's also unique in a way that I've grown to, ahem, like.

This idea makes sense to me. Since we don't authenticate anybody who wants to like a post, it would require some thought and refactoring to bring into existence as you've described.

Thoughts from others? @chriserin @dkarter

**Comment by pcapel** [comment]
So if we were to store the number of uses similarly, then people would be able to see that for themselves, and we could rate limit it similarly.  The really useful thing about it IMO is that we could then start to rank the posts along a different vector.  It could be really useful information to use in coming up with e.g. talk ideas.

**Comment by avogel3** [comment]
I wouldn't say this is completed, but closing since this is an old issue. Feel free to re-open if there is any interest in bringing the above feature to TIL
