### ISSUE TITLE
Improvement to keyboard navigation

### ISSUE THREAD

**Issue by pcapel** [hashrocket/tilex#641]
As a user, when I navigate to the site I may want to navigate to the search function without using a mouse.   Currently the tab order for the elements on the page means that I must tab through all of the posts before I reach the search. I think that it's a small fix, but putting the search as `tabindex=1` would be a small feature that would improve the usability of the site for people who don't like to take their hands off the keyboard.  Like us!

**Comment by tmock12** [comment]
👍 This is a great idea. We should probably tabindex all the icons as thats kind of the navigation menu for the site. I'll try to look into the best A11y way of doing this unless someone beats me to it.

**Comment by dkarter** [comment]
also VIM keybindings would be cool.. so `/` opens the search, and `j` / `k` jump between posts

**Comment by jwworth** [comment]
I love this idea. Have at it, @pcapel, or let us know if you'd like the group to tackle it!

As long as we're improving, or not worsening, our a11y, I am on board. I use Google Lighthouse's Assessibily Audit for this purpose. I'd love to hear if somebody has another checker or authoritative blog post to contribute. We can probably only go 'up' from where we are on this metric.

If we do Vim bindings, let's isolate that a separate issue/PR.
