### ISSUE TITLE
Upgrade DB to Postgres 12

### ISSUE THREAD

**Issue by chriserin-testdouble** [hashrocket/tilex#656]
Postgres 12 is available on Heroku, Let's Upgrade!!!

https://blog.heroku.com/posgtresql-12

If I remember right, upgrading postgres on Heroku is a painless one command operation.

**Comment by jwworth** [comment]
This is in progress.

**Comment by jwworth** [comment]
Done. I waited long enough that we're now on Postgres 13. Thank you! ❤️
