### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by jwworth** [hashrocket/tilex#671]
I'd like to see a 'dark mode' feature on TIL. You flip a toggle, and your colors change to dark mode. The browser remembers your choice. Here's an idea of what it might look like.

![image](https://user-images.githubusercontent.com/2782858/77180285-b3f4eb00-6a97-11ea-9b75-c0d8caeeffda.png)

**Comment by dkarter** [comment]
We can also use a media query to detect if the user turned on darkmode in their OS

```
@media (prefers-color-scheme: dark) {

}
```

https://css-tricks.com/dark-modes-with-css/

**Comment by jwworth** [comment]
Closing; there are several tools that can handle this without any code changes. I'm currently using Dark Reader:

https://addons.mozilla.org/en-US/firefox/addon/darkreader/
