### ISSUE TITLE
Error in the scripts

### ISSUE THREAD

**Issue by aminya** [hashrocket/tilex#703]
In https://til.hashrocket.com/posts/696df00135-remove-whitespace-changes-then-git-add-p

The script should have a `||` rather `|`
```
git diff -w --no-color || git apply --cached --ignore-whitespace && git checkout -- . && git reset && git add -p
```

Otherwise, it will throw errors

**Comment by jwworth** [comment]
I'm working on this.

**Comment by jwworth** [comment]
@aminya thanks for the report! Could you describe your reproduction steps, and the error that you're experiencing?

**Comment by aminya** [comment]
- Go to a clean git repo
- Add a space at the end of some line.
- run 
```
git diff -w --no-color | git apply --cached --ignore-whitespace && git checkout -- . && git reset && git add -p
```
- You will get:
```
error: unrecognized input
```
- No run
```
git diff -w --no-color || git apply --cached --ignore-whitespace && git checkout -- . && git reset && git add -p
```
- The error is gone. You will get 
```
No changes.
```

**Comment by jwworth** [comment]
@aminya thanks! 

I think that `||` does resolve the error. Unfortunately, it also causes the chain to short-circuit anytime `git diff` succeeds, which it should do whether there is a diff or not:

https://unix.stackexchange.com/a/159514

TIL posts are meant to be quick, get-it-done hacks; they don't always anticipate every use case. Here, the operator is intentionally running this against a diff, and `error: unrecognized input` conveys (perhaps imperfectly) that there was nothing to do. I could see somebody moving this into a script and making the 'no changes' output more user friendly.

Closing.

**Comment by aminya** [comment]
I am using this script to remove the line ending changing cause by ` actions /
upload-artifact`

https://github.com/aminya/SnoopCompile.jl/blob/multios/docs/src/bot.md#L179

**Comment by aminya** [comment]
@jwworth Regarding my script, I found out that there are some issues with it. The following works better
```bash
(git diff -w --no-color || (git diff -w --no-color | git apply --cached --ignore-whitespace && git checkout -- . && git reset && git add -p)) || echo done
```
